package com.nickhil.nickhil123;

/* Problem12: The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 * 
 * 
 * ANSWER:76576500 576 
 */

public class Problem12 {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		long i,num,factors;
		for(i=1;i<=100000;i++)
		{
			num=i*(i+1)/2;
			factors = num_of_factors(num);
			System.out.println(num+" "+factors);
			if(factors>10)
				break;
		}
	}

	private static int num_of_factors(long num) {
		int count=2;
		for(int i=2;i*i<=num;i++)
		{
			if(num%i==0)
				count+=2;
		}
		return count;
	}

}
